development:
  sessions:
    default:
      database: linknsynch_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: linknsynch_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: linknsynch_prod
      hosts:
        - localhost:27017